# Какие токены и биржи мониторим
symbols: ["BTC", "ETH", "SOL"]
# Котируемая валюта (пока одна — упрощает сравнение)
quote: "USDT"

# Минимальное преимущество (с учётом комиссий), при котором шлём сигнал в Telegram
min_edge_pct: 0.25   # 0.25% и выше

# Частота опроса API (в секундах)
poll_interval_sec: 5

# Какие биржи используем (true/false). Можно отключать, если блокирует IP.
exchanges:
  binance: true
  bybit: true
  kucoin: true
  kraken: true
  bitstamp: true
  coinbase: false   # у Coinbase чаще USD пары; включайте при необходимости

# Пример ориентировочных комиссий тейкера (можете скорректировать под свой аккаунт)
# Учитываются как на покупке, так и на продаже.
fees_taker_bps:
  binance: 10     # 0.10%
  bybit: 10
  kucoin: 10
  kraken: 26
  bitstamp: 40
  coinbase: 60

# Оценка вывода на сеть (в USDT эквиваленте) — для грубой поправки на перевод между биржами.
# Если делаете внутридневной кросс-биржевой перенос — выставьте реальные значения.
withdrawal_estimate_usdt:
  BTC: 5.0
  ETH: 2.0
  SOL: 0.02

# Дополнительные настройки Telegram (не заполняйте здесь токен/чат — они берутся из .env)
telegram:
  dry_run: false    # если true — сообщения в бот не отправляются, только лог в консоль
